<?xml version="1.0"?>
<!DOCTYPE issues [
<!ELEMENT issues (issue*)>
<!ATTLIST issues burpVersion CDATA "">
<!ATTLIST issues exportTime CDATA "">
<!ELEMENT issue (serialNumber, type, name, host, path, location, severity, confidence, issueBackground?, remediationBackground?, issueDetail?, issueDetailItems?, remediationDetail?, requestresponse*)>
<!ELEMENT serialNumber (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT host (#PCDATA)>
<!ATTLIST host ip CDATA "">
<!ELEMENT path (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT severity (#PCDATA)>
<!ELEMENT confidence (#PCDATA)>
<!ELEMENT issueBackground (#PCDATA)>
<!ELEMENT remediationBackground (#PCDATA)>
<!ELEMENT issueDetail (#PCDATA)>
<!ELEMENT issueDetailItems (issueDetailItem*)>
<!ELEMENT issueDetailItem (#PCDATA)>
<!ELEMENT remediationDetail (#PCDATA)>
<!ELEMENT requestresponse (request?, response?, responseRedirected?)>
<!ELEMENT request (#PCDATA)>
<!ATTLIST request method CDATA "">
<!ATTLIST request base64 (true|false) "false">
<!ELEMENT response (#PCDATA)>
<!ATTLIST response base64 (true|false) "false">
<!ELEMENT responseRedirected (#PCDATA)>
]>
<issues burpVersion="1.6.05" exportTime="Sat Sep 13 22:35:04 CEST 2014">
  <issue>
    <serialNumber>3198286154699013120</serialNumber>
    <type>5245344</type>
    <name>Frameable response (potential Clickjacking)</name>
    <host ip="192.168.187.137">http://bwa</host>
    <path><![CDATA[/bodgeit/]]></path>
    <location><![CDATA[/bodgeit/]]></location>
    <severity>Information</severity>
    <confidence>Firm</confidence>
    <issueBackground><![CDATA[It might be possible for a web page controlled by an attacker to load the content of this response within an iframe on the attacker's page. This may enable a "clickjacking" attack, in which the attacker's page overlays the target application's interface with a different interface provided by the attacker. By inducing victim users to perform actions such as mouse clicks and keystrokes, the attacker can cause them to unwittingly carry out actions within the application that is being targeted. This technique allows the attacker to circumvent defenses against cross-site request forgery, and may result in unauthorized actions.<br><br>Note that this issue is being reported because the application's response does not set a suitable <b>X-Frame-Options</b> header in order to prevent framing attacks. Some applications attempt to prevent these attacks from within the HTML page itself, using "framebusting" code. However, this type of defense is normally ineffective and can usually be circumvented by a skilled attacker.]]></issueBackground>
    <remediationBackground><![CDATA[You should review the application functions that are accessible from within the response, and determine whether they can be used by application users to perform any sensitive actions within the application. If so, then a framing attack targeting this response may result in unauthorized actions.<br><br>To effectively prevent framing attacks, the application should return a response header with the name <b>X-Frame-Options</b> and the value <b>DENY</b> to prevent framing altogether, or the value <b>SAMEORIGIN</b> to allow framing only by pages on the same origin as the response itself.]]></remediationBackground>
    <requestresponse>
      <request method="GET" base64="true"><![CDATA[R0VUIC9ib2RnZWl0LyBIVFRQLzEuMQ0KSG9zdDogYndhDQpVc2VyLUFnZW50OiBNb3ppbGxhLzUuMCAoV2luZG93cyBOVCA2LjE7IFdPVzY0OyBydjozMS4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzMxLjANCkFjY2VwdDogdGV4dC9odG1sLGFwcGxpY2F0aW9uL3hodG1sK3htbCxhcHBsaWNhdGlvbi94bWw7cT0wLjksKi8qO3E9MC44DQpBY2NlcHQtTGFuZ3VhZ2U6IGVuLVVTLGVuO3E9MC41DQpBY2NlcHQtRW5jb2Rpbmc6IGd6aXAsIGRlZmxhdGUNCkNvb2tpZTogYWNvcGVuZGl2aWRzPXN3aW5nc2V0LGpvdHRvLHBocGJiMixyZWRtaW5lOyBhY2dyb3Vwc3dpdGhwZXJzaXN0PW5hZGE7IEpTRVNTSU9OSUQ9QUQwMDI0MEE5MzI4MzVFREQ2MEIzRjc0ODdBOUQxNUQ7IFBIUFNFU1NJRD1oc2k2cXExYmJwOGdyZzZhaGo5NXMxdWR2NA0KQ29ubmVjdGlvbjoga2VlcC1hbGl2ZQ0KDQo=]]></request>
      <response base64="true"><![CDATA[SFRUUC8xLjEgMjAwIE9LDQpEYXRlOiBTYXQsIDEzIFNlcCAyMDE0IDIwOjE1OjIzIEdNVA0KU2VydmVyOiBBcGFjaGUtQ295b3RlLzEuMQ0KQ29udGVudC1UeXBlOiB0ZXh0L2h0bWwNClNldC1Db29raWU6IEpTRVNTSU9OSUQ9QUQwMDI0MEE5MzI4MzVFREQ2MEIzRjc0ODdBOUQxNUQ7IFBhdGg9Lw0KVmlhOiAxLjEgMTI3LjAuMS4xDQpWYXJ5OiBBY2NlcHQtRW5jb2RpbmcNCkNvbnRlbnQtTGVuZ3RoOiAzMTc3DQpLZWVwLUFsaXZlOiB0aW1lb3V0PTE1LCBtYXg9MTAwDQpDb25uZWN0aW9uOiBLZWVwLUFsaXZlDQoNCgoKCgoKCgoKPCFET0NUWVBFIEhUTUwgUFVCTElDICItLy9XM0MvL0RURCBIVE1MIDMuMi8vRU4iPgo8aHRtbD4KPGhlYWQ+Cjx0aXRsZT5UaGUgQm9kZ2VJdCBTdG9yZTwvdGl0bGU+CjxsaW5rIGhyZWY9InN0eWxlLmNzcyIgcmVsPSJzdHlsZXNoZWV0IiB0eXBlPSJ0ZXh0L2NzcyIgLz4KPHNjcmlwdCB0eXBlPSJ0ZXh0L2phdmFzY3JpcHQiIHNyYz0iLi9qcy91dGlsLmpzIj48L3NjcmlwdD4KPC9oZWFkPgo8Ym9keT4KCjxjZW50ZXI+Cjx0YWJsZSB3aWR0aD0iODAlIiBjbGFzcz0iYm9yZGVyIj4KPHRyIEJHQ09MT1I9I0MzRDlGRj4KPHRkIGFsaWduPSJjZW50ZXIiIGNvbHNwYW49IjYiPgo8SDE+VGhlIEJvZGdlSXQgU3RvcmU8L0gxPgo8dGFibGUgd2lkdGg9IjEwMCUiIGNsYXNzPVwibm9ib3JkZXJcIj4KPHRyIEJHQ09MT1I9I0MzRDlGRj4KPHRkIGFsaWduPSJjZW50ZXIiIHdpZHRoPSIzMCUiPiZuYnNwOzwvdGQ+Cjx0ZCBhbGlnbj0iY2VudGVyIiB3aWR0aD0iNDAlIj5XZSBib2RnZSBpdCwgc28geW91IGRvbnQgaGF2ZSB0byE8L3RkPgo8dGQgYWxpZ249ImNlbnRlciIgd2lkdGg9IjMwJSIgc3R5bGU9InRleHQtYWxpZ246IHJpZ2h0IiA+Ckd1ZXN0IHVzZXIKCjwvdHI+CjwvdGFibGU+CjwvdGQ+CjwvdHI+Cjx0cj4KPHRkIGFsaWduPSJjZW50ZXIiIHdpZHRoPSIxNiUiIEJHQ09MT1I9I0VFRUVFRT48YSBocmVmPSJob21lLmpzcCI+SG9tZTwvYT48L3RkPgo8dGQgYWxpZ249ImNlbnRlciIgd2lkdGg9IjE2JSIgQkdDT0xPUj0jRUVFRUVFPjxhIGhyZWY9ImFib3V0LmpzcCI+QWJvdXQgVXM8L2E+PC90ZD4KCjx0ZCBhbGlnbj0iY2VudGVyIiB3aWR0aD0iMTYlIiBCR0NPTE9SPSNFRUVFRUU+PGEgaHJlZj0iY29udGFjdC5qc3AiPkNvbnRhY3QgVXM8L2E+PC90ZD4KPCEtLSB0ZCBhbGlnbj0iY2VudGVyIiB3aWR0aD0iMTYlIj48YSBocmVmPSJhZG1pbi5qc3AiPkFkbWluPC9hPjwvdGQtLT4KCjx0ZCBhbGlnbj0iY2VudGVyIiB3aWR0aD0iMTYlIiBCR0NPTE9SPSNFRUVFRUU+CgoJCTxhIGhyZWY9ImxvZ2luLmpzcCI+TG9naW48L2E+Cgo8L3RkPgoKPHRkIGFsaWduPSJjZW50ZXIiIHdpZHRoPSIxNiUiIEJHQ09MT1I9I0VFRUVFRT48YSBocmVmPSJiYXNrZXQuanNwIj5Zb3VyIEJhc2tldDwvYT48L3RkPgoKPHRkIGFsaWduPSJjZW50ZXIiIHdpZHRoPSIxNiUiIEJHQ09MT1I9I0VFRUVFRT48YSBocmVmPSJzZWFyY2guanNwIj5TZWFyY2g8L2E+PC90ZD4KPC90cj4KPHRyPgo8dGQgYWxpZ249ImNlbnRlciIgY29sc3Bhbj0iNiI+Cjx0YWJsZSB3aWR0aD0iMTAwJSIgY2xhc3M9ImJvcmRlciI+Cjx0cj4KPHRkIGFsaWduPSJsZWZ0IiB2YWxpZ249InRvcCIgd2lkdGg9IjI1JSI+CjxhIGhyZWY9InByb2R1Y3QuanNwP3R5cGVpZD02Ij5Eb29kYWhzPC9hPjxici8+CjxhIGhyZWY9InByb2R1Y3QuanNwP3R5cGVpZD01Ij5HaXptb3M8L2E+PGJyLz4KPGEgaHJlZj0icHJvZHVjdC5qc3A/dHlwZWlkPTMiPlRoaW5nYW1hamlnczwvYT48YnIvPgo8YSBocmVmPSJwcm9kdWN0LmpzcD90eXBlaWQ9MiI+VGhpbmdpZXM8L2E+PGJyLz4KPGEgaHJlZj0icHJvZHVjdC5qc3A/dHlwZWlkPTciPldoYXRjaGFtYWNhbGxpdHM8L2E+PGJyLz4KPGEgaHJlZj0icHJvZHVjdC5qc3A/dHlwZWlkPTQiPldoYXRzaXRzPC9hPjxici8+CjxhIGhyZWY9InByb2R1Y3QuanNwP3R5cGVpZD0xIj5XaWRnZXRzPC9hPjxici8+Cgo8YnIvPjxici8+PGJyLz48YnIvPjxici8+PGJyLz48YnIvPjxici8+PGJyLz48YnIvPjxici8+PGJyLz48YnIvPjxici8+PGJyLz4KPC90ZD4KPHRkIHZhbGlnbj0idG9wIiB3aWR0aD0iNzAlIj4KCgo8aDM+T3VyIEJlc3QgRGVhbHMhPC9oMz4KPGNlbnRlcj48dGFibGUgYm9yZGVyPSIxIiBjbGFzcz0iYm9yZGVyIiB3aWR0aD0iODAlIj4KPHRyPjx0aD5Qcm9kdWN0PC90aD48dGg+VHlwZTwvdGg+PHRoPlByaWNlPC90aD48L3RyPgo8dHI+Cjx0ZD48YSBocmVmPSJwcm9kdWN0LmpzcD9wcm9kaWQ9MTIiPlRHSiBDQ0Q8L2E+PC90ZD48dGQ+VGhpbmdhbWFqaWdzPC90ZD48dGQgYWxpZ249InJpZ2h0Ij4kMi4yMDwvdGQ+CjwvdHI+Cjx0cj4KPHRkPjxhIGhyZWY9InByb2R1Y3QuanNwP3Byb2RpZD0yIj5Db21wbGV4IFdpZGdldDwvYT48L3RkPjx0ZD5XaWRnZXRzPC90ZD48dGQgYWxpZ249InJpZ2h0Ij4kMy4xMDwvdGQ+CjwvdHI+Cjx0cj4KPHRkPjxhIGhyZWY9InByb2R1Y3QuanNwP3Byb2RpZD0zIj5XZWlyZCBXaWRnZXQ8L2E+PC90ZD48dGQ+V2lkZ2V0czwvdGQ+PHRkIGFsaWduPSJyaWdodCI+JDQuNzA8L3RkPgo8L3RyPgo8dHI+Cjx0ZD48YSBocmVmPSJwcm9kdWN0LmpzcD9wcm9kaWQ9OCI+VGhpbmdpZSA1PC9hPjwvdGQ+PHRkPlRoaW5naWVzPC90ZD48dGQgYWxpZ249InJpZ2h0Ij4kMy43MDwvdGQ+CjwvdHI+Cjx0cj4KPHRkPjxhIGhyZWY9InByb2R1Y3QuanNwP3Byb2RpZD0xIj5CYXNpYyBXaWRnZXQ8L2E+PC90ZD48dGQ+V2lkZ2V0czwvdGQ+PHRkIGFsaWduPSJyaWdodCI+JDEuMjA8L3RkPgo8L3RyPgo8dHI+Cjx0ZD48YSBocmVmPSJwcm9kdWN0LmpzcD9wcm9kaWQ9MSI+QmFzaWMgV2lkZ2V0PC9hPjwvdGQ+PHRkPldpZGdldHM8L3RkPjx0ZCBhbGlnbj0icmlnaHQiPiQxLjIwPC90ZD4KPC90cj4KPHRyPgo8dGQ+PGEgaHJlZj0icHJvZHVjdC5qc3A/cHJvZGlkPTI5Ij5UaXBvZm15dG9uZ3VlPC9hPjwvdGQ+PHRkPldoYXRjaGFtYWNhbGxpdHM8L3RkPjx0ZCBhbGlnbj0icmlnaHQiPiQzLjc0PC90ZD4KPC90cj4KPHRyPgo8dGQ+PGEgaHJlZj0icHJvZHVjdC5qc3A/cHJvZGlkPTciPlRoaW5naWUgNDwvYT48L3RkPjx0ZD5UaGluZ2llczwvdGQ+PHRkIGFsaWduPSJyaWdodCI+JDMuNTA8L3RkPgo8L3RyPgo8dHI+Cjx0ZD48YSBocmVmPSJwcm9kdWN0LmpzcD9wcm9kaWQ9MTQiPlRHSiBHR0c8L2E+PC90ZD48dGQ+VGhpbmdhbWFqaWdzPC90ZD48dGQgYWxpZ249InJpZ2h0Ij4kMi42MDwvdGQ+CjwvdHI+Cjx0cj4KPHRkPjxhIGhyZWY9InByb2R1Y3QuanNwP3Byb2RpZD0yNSI+R1ogSzc3PC9hPjwvdGQ+PHRkPkdpem1vczwvdGQ+PHRkIGFsaWduPSJyaWdodCI+JDMuMDU8L3RkPgo8L3RyPgo8L3RhYmxlPjwvY2VudGVyPjxici8+CgoKPC90ZD4KPC90cj4KPC90YWJsZT4KPC90ZD4KPC90cj4KPC90YWJsZT4KPC9jZW50ZXI+CjwvYm9keT4KPC9odG1sPgoKCg==]]></response>
      <responseRedirected>false</responseRedirected>
    </requestresponse>
  </issue>
  <issue>
    <serialNumber>2058623172267370496</serialNumber>
    <type>5245344</type>
    <name>Frameable response (potential Clickjacking)</name>
    <host ip="192.168.187.137">http://bwa</host>
    <path><![CDATA[/bodgeit/search.jsp]]></path>
    <location><![CDATA[/bodgeit/search.jsp]]></location>
    <severity>Information</severity>
    <confidence>Firm</confidence>
    <issueBackground><![CDATA[It might be possible for a web page controlled by an attacker to load the content of this response within an iframe on the attacker's page. This may enable a "clickjacking" attack, in which the attacker's page overlays the target application's interface with a different interface provided by the attacker. By inducing victim users to perform actions such as mouse clicks and keystrokes, the attacker can cause them to unwittingly carry out actions within the application that is being targeted. This technique allows the attacker to circumvent defenses against cross-site request forgery, and may result in unauthorized actions.<br><br>Note that this issue is being reported because the application's response does not set a suitable <b>X-Frame-Options</b> header in order to prevent framing attacks. Some applications attempt to prevent these attacks from within the HTML page itself, using "framebusting" code. However, this type of defense is normally ineffective and can usually be circumvented by a skilled attacker.]]></issueBackground>
    <remediationBackground><![CDATA[You should review the application functions that are accessible from within the response, and determine whether they can be used by application users to perform any sensitive actions within the application. If so, then a framing attack targeting this response may result in unauthorized actions.<br><br>To effectively prevent framing attacks, the application should return a response header with the name <b>X-Frame-Options</b> and the value <b>DENY</b> to prevent framing altogether, or the value <b>SAMEORIGIN</b> to allow framing only by pages on the same origin as the response itself.]]></remediationBackground>
    <requestresponse>
      <request method="GET" base64="true"><![CDATA[R0VUIC9ib2RnZWl0L3NlYXJjaC5qc3A/cT01NTUtNTU1LTAxOTlAZXhhbXBsZS5jb20gSFRUUC8xLjENCkhvc3Q6IGJ3YQ0KQWNjZXB0OiAqLyoNCkFjY2VwdC1MYW5ndWFnZTogZW4NClVzZXItQWdlbnQ6IE1vemlsbGEvNS4wIChjb21wYXRpYmxlOyBNU0lFIDkuMDsgV2luZG93cyBOVCA2LjE7IFdpbjY0OyB4NjQ7IFRyaWRlbnQvNS4wKQ0KQ29ubmVjdGlvbjogY2xvc2UNClJlZmVyZXI6IGh0dHA6Ly9id2EvYm9kZ2VpdC9zZWFyY2guanNwDQpDb29raWU6IGFjb3BlbmRpdmlkcz1zd2luZ3NldCxqb3R0byxwaHBiYjIscmVkbWluZTsgYWNncm91cHN3aXRocGVyc2lzdD1uYWRhOyBKU0VTU0lPTklEPUFEMDAyNDBBOTMyODM1RURENjBCM0Y3NDg3QTlEMTVEOyBQSFBTRVNTSUQ9aHNpNnFxMWJicDhncmc2YWhqOTVzMXVkdjQ7IGJfaWQ9OTUNCg0K]]></request>
      <response base64="true"><![CDATA[SFRUUC8xLjEgMjAwIE9LDQpEYXRlOiBTYXQsIDEzIFNlcCAyMDE0IDIwOjI1OjI0IEdNVA0KU2VydmVyOiBBcGFjaGUtQ295b3RlLzEuMQ0KQ29udGVudC1UeXBlOiB0ZXh0L2h0bWwNCkNvbnRlbnQtTGVuZ3RoOiAyMDI5DQpWaWE6IDEuMSAxMjcuMC4xLjENClZhcnk6IEFjY2VwdC1FbmNvZGluZw0KQ29ubmVjdGlvbjogY2xvc2UNCg0KCgoKCgoKCjwhRE9DVFlQRSBIVE1MIFBVQkxJQyAiLS8vVzNDLy9EVEQgSFRNTCAzLjIvL0VOIj4KPGh0bWw+CjxoZWFkPgo8dGl0bGU+VGhlIEJvZGdlSXQgU3RvcmU8L3RpdGxlPgo8bGluayBocmVmPSJzdHlsZS5jc3MiIHJlbD0ic3R5bGVzaGVldCIgdHlwZT0idGV4dC9jc3MiIC8+CjxzY3JpcHQgdHlwZT0idGV4dC9qYXZhc2NyaXB0IiBzcmM9Ii4vanMvdXRpbC5qcyI+PC9zY3JpcHQ+CjwvaGVhZD4KPGJvZHk+Cgo8Y2VudGVyPgo8dGFibGUgd2lkdGg9IjgwJSIgY2xhc3M9ImJvcmRlciI+Cjx0ciBCR0NPTE9SPSNDM0Q5RkY+Cjx0ZCBhbGlnbj0iY2VudGVyIiBjb2xzcGFuPSI2Ij4KPEgxPlRoZSBCb2RnZUl0IFN0b3JlPC9IMT4KPHRhYmxlIHdpZHRoPSIxMDAlIiBjbGFzcz1cIm5vYm9yZGVyXCI+Cjx0ciBCR0NPTE9SPSNDM0Q5RkY+Cjx0ZCBhbGlnbj0iY2VudGVyIiB3aWR0aD0iMzAlIj4mbmJzcDs8L3RkPgo8dGQgYWxpZ249ImNlbnRlciIgd2lkdGg9IjQwJSI+V2UgYm9kZ2UgaXQsIHNvIHlvdSBkb250IGhhdmUgdG8hPC90ZD4KPHRkIGFsaWduPSJjZW50ZXIiIHdpZHRoPSIzMCUiIHN0eWxlPSJ0ZXh0LWFsaWduOiByaWdodCIgPgpHdWVzdCB1c2VyCgo8L3RyPgo8L3RhYmxlPgo8L3RkPgo8L3RyPgo8dHI+Cjx0ZCBhbGlnbj0iY2VudGVyIiB3aWR0aD0iMTYlIiBCR0NPTE9SPSNFRUVFRUU+PGEgaHJlZj0iaG9tZS5qc3AiPkhvbWU8L2E+PC90ZD4KPHRkIGFsaWduPSJjZW50ZXIiIHdpZHRoPSIxNiUiIEJHQ09MT1I9I0VFRUVFRT48YSBocmVmPSJhYm91dC5qc3AiPkFib3V0IFVzPC9hPjwvdGQ+Cgo8dGQgYWxpZ249ImNlbnRlciIgd2lkdGg9IjE2JSIgQkdDT0xPUj0jRUVFRUVFPjxhIGhyZWY9ImNvbnRhY3QuanNwIj5Db250YWN0IFVzPC9hPjwvdGQ+CjwhLS0gdGQgYWxpZ249ImNlbnRlciIgd2lkdGg9IjE2JSI+PGEgaHJlZj0iYWRtaW4uanNwIj5BZG1pbjwvYT48L3RkLS0+Cgo8dGQgYWxpZ249ImNlbnRlciIgd2lkdGg9IjE2JSIgQkdDT0xPUj0jRUVFRUVFPgoKCQk8YSBocmVmPSJsb2dpbi5qc3AiPkxvZ2luPC9hPgoKPC90ZD4KCjx0ZCBhbGlnbj0iY2VudGVyIiB3aWR0aD0iMTYlIiBCR0NPTE9SPSNFRUVFRUU+PGEgaHJlZj0iYmFza2V0LmpzcCI+WW91ciBCYXNrZXQ8L2E+PC90ZD4KCjx0ZCBhbGlnbj0iY2VudGVyIiB3aWR0aD0iMTYlIiBCR0NPTE9SPSNFRUVFRUU+PGEgaHJlZj0ic2VhcmNoLmpzcCI+U2VhcmNoPC9hPjwvdGQ+CjwvdHI+Cjx0cj4KPHRkIGFsaWduPSJjZW50ZXIiIGNvbHNwYW49IjYiPgo8dGFibGUgd2lkdGg9IjEwMCUiIGNsYXNzPSJib3JkZXIiPgo8dHI+Cjx0ZCBhbGlnbj0ibGVmdCIgdmFsaWduPSJ0b3AiIHdpZHRoPSIyNSUiPgo8YSBocmVmPSJwcm9kdWN0LmpzcD90eXBlaWQ9NiI+RG9vZGFoczwvYT48YnIvPgo8YSBocmVmPSJwcm9kdWN0LmpzcD90eXBlaWQ9NSI+R2l6bW9zPC9hPjxici8+CjxhIGhyZWY9InByb2R1Y3QuanNwP3R5cGVpZD0zIj5UaGluZ2FtYWppZ3M8L2E+PGJyLz4KPGEgaHJlZj0icHJvZHVjdC5qc3A/dHlwZWlkPTIiPlRoaW5naWVzPC9hPjxici8+CjxhIGhyZWY9InByb2R1Y3QuanNwP3R5cGVpZD03Ij5XaGF0Y2hhbWFjYWxsaXRzPC9hPjxici8+CjxhIGhyZWY9InByb2R1Y3QuanNwP3R5cGVpZD00Ij5XaGF0c2l0czwvYT48YnIvPgo8YSBocmVmPSJwcm9kdWN0LmpzcD90eXBlaWQ9MSI+V2lkZ2V0czwvYT48YnIvPgoKPGJyLz48YnIvPjxici8+PGJyLz48YnIvPjxici8+PGJyLz48YnIvPjxici8+PGJyLz48YnIvPjxici8+PGJyLz48YnIvPjxici8+CjwvdGQ+Cjx0ZCB2YWxpZ249InRvcCIgd2lkdGg9IjcwJSI+Cgo8aDM+U2VhcmNoPC9oMz4KPGZvbnQgc2l6ZT0iLTEiPgoKPGI+WW91IHNlYXJjaGVkIGZvcjo8L2I+IDU1NS01NTUtMDE5OUBleGFtcGxlLmNvbTxici8+PGJyLz4KPGRpdj48Yj5ObyBSZXN1bHRzIEZvdW5kPC9iPjwvZGl2PgoKPC9mb250Pgo8L3RkPgo8L3RyPgo8L3RhYmxlPgo8L3RkPgo8L3RyPgo8L3RhYmxlPgo8L2NlbnRlcj4KPC9ib2R5Pgo8L2h0bWw+Cg==]]></response>
      <responseRedirected>false</responseRedirected>
    </requestresponse>
  </issue>
  <issue>
    <serialNumber>8138735078627461120</serialNumber>
    <type>8389120</type>
    <name>HTML does not specify charset</name>
    <host ip="192.168.187.137">http://bwa</host>
    <path><![CDATA[/bodgeit/login.jsp]]></path>
    <location><![CDATA[/bodgeit/login.jsp]]></location>
    <severity>Information</severity>
    <confidence>Certain</confidence>
    <issueBackground><![CDATA[If a web response states that it contains HTML content but does not specify a character set, then the browser may analyze the HTML and attempt to determine which character set it appears to be using. Even if the majority of the HTML actually employs a standard character set such as UTF-8, the presence of non-standard characters anywhere in the response may cause the browser to interpret the content using a different character set. This can have unexpected results, and can lead to cross-site scripting vulnerabilities in which non-standard encodings like UTF-7 can be used to bypass the application's defensive filters.<br><br>In most cases, the absence of a charset directive does not constitute a security flaw, particularly if the response contains static content. You should review the contents of the response and the context in which it appears to determine whether any vulnerability exists.]]></issueBackground>
    <remediationBackground><![CDATA[For every response containing HTML content, the application should include within the Content-type header a directive specifying a standard recognized character set, for example <b>charset=ISO-8859-1</b>.]]></remediationBackground>
    <requestresponse>
      <request method="POST" base64="true"><![CDATA[UE9TVCAvYm9kZ2VpdC9sb2dpbi5qc3AgSFRUUC8xLjENCkhvc3Q6IGJ3YQ0KQWNjZXB0OiAqLyoNCkFjY2VwdC1MYW5ndWFnZTogZW4NClVzZXItQWdlbnQ6IE1vemlsbGEvNS4wIChjb21wYXRpYmxlOyBNU0lFIDkuMDsgV2luZG93cyBOVCA2LjE7IFdpbjY0OyB4NjQ7IFRyaWRlbnQvNS4wKQ0KQ29ubmVjdGlvbjogY2xvc2UNClJlZmVyZXI6IGh0dHA6Ly9id2EvYm9kZ2VpdC9sb2dpbi5qc3ANCkNvbnRlbnQtVHlwZTogYXBwbGljYXRpb24veC13d3ctZm9ybS11cmxlbmNvZGVkDQpDb250ZW50LUxlbmd0aDogMjkNCkNvb2tpZTogYWNvcGVuZGl2aWRzPXN3aW5nc2V0LGpvdHRvLHBocGJiMixyZWRtaW5lOyBhY2dyb3Vwc3dpdGhwZXJzaXN0PW5hZGE7IEpTRVNTSU9OSUQ9QUQwMDI0MEE5MzI4MzVFREQ2MEIzRjc0ODdBOUQxNUQ7IFBIUFNFU1NJRD1oc2k2cXExYmJwOGdyZzZhaGo5NXMxdWR2NDsgYl9pZD05NQ0KDQp1c2VybmFtZT10ZXN0MSZwYXNzd29yZD10ZXN0Mg==]]></request>
      <response base64="true"><![CDATA[SFRUUC8xLjEgMjAwIE9LDQpEYXRlOiBTYXQsIDEzIFNlcCAyMDE0IDIwOjI1OjI0IEdNVA0KU2VydmVyOiBBcGFjaGUtQ295b3RlLzEuMQ0KQ29udGVudC1UeXBlOiB0ZXh0L2h0bWwNCkNvbnRlbnQtTGVuZ3RoOiAyNTI5DQpWaWE6IDEuMSAxMjcuMC4xLjENClZhcnk6IEFjY2VwdC1FbmNvZGluZw0KQ29ubmVjdGlvbjogY2xvc2UNCg0KDQoNCg0KDQoKCgoKPCFET0NUWVBFIEhUTUwgUFVCTElDICItLy9XM0MvL0RURCBIVE1MIDMuMi8vRU4iPgo8aHRtbD4KPGhlYWQ+Cjx0aXRsZT5UaGUgQm9kZ2VJdCBTdG9yZTwvdGl0bGU+CjxsaW5rIGhyZWY9InN0eWxlLmNzcyIgcmVsPSJzdHlsZXNoZWV0IiB0eXBlPSJ0ZXh0L2NzcyIgLz4KPHNjcmlwdCB0eXBlPSJ0ZXh0L2phdmFzY3JpcHQiIHNyYz0iLi9qcy91dGlsLmpzIj48L3NjcmlwdD4KPC9oZWFkPgo8Ym9keT4KCjxjZW50ZXI+Cjx0YWJsZSB3aWR0aD0iODAlIiBjbGFzcz0iYm9yZGVyIj4KPHRyIEJHQ09MT1I9I0MzRDlGRj4KPHRkIGFsaWduPSJjZW50ZXIiIGNvbHNwYW49IjYiPgo8SDE+VGhlIEJvZGdlSXQgU3RvcmU8L0gxPgo8dGFibGUgd2lkdGg9IjEwMCUiIGNsYXNzPVwibm9ib3JkZXJcIj4KPHRyIEJHQ09MT1I9I0MzRDlGRj4KPHRkIGFsaWduPSJjZW50ZXIiIHdpZHRoPSIzMCUiPiZuYnNwOzwvdGQ+Cjx0ZCBhbGlnbj0iY2VudGVyIiB3aWR0aD0iNDAlIj5XZSBib2RnZSBpdCwgc28geW91IGRvbnQgaGF2ZSB0byE8L3RkPgo8dGQgYWxpZ249ImNlbnRlciIgd2lkdGg9IjMwJSIgc3R5bGU9InRleHQtYWxpZ246IHJpZ2h0IiA+Ckd1ZXN0IHVzZXIKCjwvdHI+CjwvdGFibGU+CjwvdGQ+CjwvdHI+Cjx0cj4KPHRkIGFsaWduPSJjZW50ZXIiIHdpZHRoPSIxNiUiIEJHQ09MT1I9I0VFRUVFRT48YSBocmVmPSJob21lLmpzcCI+SG9tZTwvYT48L3RkPgo8dGQgYWxpZ249ImNlbnRlciIgd2lkdGg9IjE2JSIgQkdDT0xPUj0jRUVFRUVFPjxhIGhyZWY9ImFib3V0LmpzcCI+QWJvdXQgVXM8L2E+PC90ZD4KCjx0ZCBhbGlnbj0iY2VudGVyIiB3aWR0aD0iMTYlIiBCR0NPTE9SPSNFRUVFRUU+PGEgaHJlZj0iY29udGFjdC5qc3AiPkNvbnRhY3QgVXM8L2E+PC90ZD4KPCEtLSB0ZCBhbGlnbj0iY2VudGVyIiB3aWR0aD0iMTYlIj48YSBocmVmPSJhZG1pbi5qc3AiPkFkbWluPC9hPjwvdGQtLT4KCjx0ZCBhbGlnbj0iY2VudGVyIiB3aWR0aD0iMTYlIiBCR0NPTE9SPSNFRUVFRUU+CgoJCTxhIGhyZWY9ImxvZ2luLmpzcCI+TG9naW48L2E+Cgo8L3RkPgoKPHRkIGFsaWduPSJjZW50ZXIiIHdpZHRoPSIxNiUiIEJHQ09MT1I9I0VFRUVFRT48YSBocmVmPSJiYXNrZXQuanNwIj5Zb3VyIEJhc2tldDwvYT48L3RkPgoKPHRkIGFsaWduPSJjZW50ZXIiIHdpZHRoPSIxNiUiIEJHQ09MT1I9I0VFRUVFRT48YSBocmVmPSJzZWFyY2guanNwIj5TZWFyY2g8L2E+PC90ZD4KPC90cj4KPHRyPgo8dGQgYWxpZ249ImNlbnRlciIgY29sc3Bhbj0iNiI+Cjx0YWJsZSB3aWR0aD0iMTAwJSIgY2xhc3M9ImJvcmRlciI+Cjx0cj4KPHRkIGFsaWduPSJsZWZ0IiB2YWxpZ249InRvcCIgd2lkdGg9IjI1JSI+CjxhIGhyZWY9InByb2R1Y3QuanNwP3R5cGVpZD02Ij5Eb29kYWhzPC9hPjxici8+CjxhIGhyZWY9InByb2R1Y3QuanNwP3R5cGVpZD01Ij5HaXptb3M8L2E+PGJyLz4KPGEgaHJlZj0icHJvZHVjdC5qc3A/dHlwZWlkPTMiPlRoaW5nYW1hamlnczwvYT48YnIvPgo8YSBocmVmPSJwcm9kdWN0LmpzcD90eXBlaWQ9MiI+VGhpbmdpZXM8L2E+PGJyLz4KPGEgaHJlZj0icHJvZHVjdC5qc3A/dHlwZWlkPTciPldoYXRjaGFtYWNhbGxpdHM8L2E+PGJyLz4KPGEgaHJlZj0icHJvZHVjdC5qc3A/dHlwZWlkPTQiPldoYXRzaXRzPC9hPjxici8+CjxhIGhyZWY9InByb2R1Y3QuanNwP3R5cGVpZD0xIj5XaWRnZXRzPC9hPjxici8+Cgo8YnIvPjxici8+PGJyLz48YnIvPjxici8+PGJyLz48YnIvPjxici8+PGJyLz48YnIvPjxici8+PGJyLz48YnIvPjxici8+PGJyLz4KPC90ZD4KPHRkIHZhbGlnbj0idG9wIiB3aWR0aD0iNzAlIj4KDQo8cCBzdHlsZT0iY29sb3I6cmVkIj5Zb3Ugc3VwcGxpZWQgYW4gaW52YWxpZCBuYW1lIG9yIHBhc3N3b3JkLjwvcD4KDQo8aDM+TG9naW48L2gzPg0KUGxlYXNlIGVudGVyIHlvdXIgY3JlZGVudGlhbHM6IDxici8+PGJyLz4NCjxmb3JtIG1ldGhvZD0iUE9TVCI+DQoJPGNlbnRlcj4NCgk8dGFibGU+DQoJPHRyPg0KCQk8dGQ+VXNlcm5hbWU6PC90ZD4NCgkJPHRkPjxpbnB1dCBpZD0idXNlcm5hbWUiIG5hbWU9InVzZXJuYW1lIj48L2lucHV0PjwvdGQ+DQoJPC90cj4NCgk8dHI+DQoJCTx0ZD5QYXNzd29yZDo8L3RkPg0KCQk8dGQ+PGlucHV0IGlkPSJwYXNzd29yZCIgbmFtZT0icGFzc3dvcmQiIHR5cGU9InBhc3N3b3JkIj48L2lucHV0PjwvdGQ+DQoJPC90cj4NCgk8dHI+DQoJCTx0ZD48L3RkPg0KCQk8dGQ+PGlucHV0IGlkPSJzdWJtaXQiIHR5cGU9InN1Ym1pdCIgdmFsdWU9IkxvZ2luIj48L2lucHV0PjwvdGQ+DQoJPC90cj4NCgk8L3RhYmxlPg0KCTwvY2VudGVyPg0KPC9mb3JtPg0KSWYgeW91IGRvbnQgaGF2ZSBhbiBhY2NvdW50IHdpdGggdXMgdGhlbiBwbGVhc2UgPGEgaHJlZj0icmVnaXN0ZXIuanNwIj5SZWdpc3RlcjwvYT4gbm93IGZvciBhIGZyZWUgYWNjb3VudC4NCjxici8+PGJyLz4NCg0KPC90ZD4KPC90cj4KPC90YWJsZT4KPC90ZD4KPC90cj4KPC90YWJsZT4KPC9jZW50ZXI+CjwvYm9keT4KPC9odG1sPgoNCg0K]]></response>
      <responseRedirected>false</responseRedirected>
    </requestresponse>
  </issue>
  <issue>
    <serialNumber>1136920954635853824</serialNumber>
    <type>2097920</type>
    <name>Cross-site scripting (reflected)</name>
    <host ip="192.168.187.137">http://bwa</host>
    <path><![CDATA[/bodgeit/search.jsp]]></path>
    <location><![CDATA[/bodgeit/search.jsp [q parameter]]]></location>
    <severity>High</severity>
    <confidence>Certain</confidence>
    <issueBackground><![CDATA[Reflected cross-site scripting vulnerabilities arise when data is copied from a request and echoed into the application's immediate response in an unsafe way. An attacker can use the vulnerability to construct a request which, if issued by another application user, will cause JavaScript code supplied by the attacker to execute within the user's browser in the context of that user's session with the application.<br><br>The attacker-supplied code can perform a wide variety of actions, such as stealing the victim's session token or login credentials, performing arbitrary actions on the victim's behalf, and logging their keystrokes.<br><br>Users can be induced to issue the attacker's crafted request in various ways. For example, the attacker can send a victim a link containing a malicious URL in an email or instant message. They can submit the link to popular web sites that allow content authoring, for example in blog comments. And they can create an innocuous looking web site which causes anyone viewing it to make arbitrary cross-domain requests to the vulnerable application (using either the GET or the POST method).<br><br>The security impact of cross-site scripting vulnerabilities is dependent upon the nature of the vulnerable application, the kinds of data and functionality which it contains, and the other applications which belong to the same domain and organization. If the application is used only to display non-sensitive public content, with no authentication or access control functionality, then a cross-site scripting flaw may be considered low risk. However, if the same application resides on a domain which can access cookies for other more security-critical applications, then the vulnerability could be used to attack those other applications, and so may be considered high risk. Similarly, if the organization which owns the application is a likely target for phishing attacks, then the vulnerability could be leveraged to lend credibility to such attacks, by injecting Trojan functionality into the vulnerable application, and exploiting users' trust in the organization in order to capture credentials for other applications which it owns. In many kinds of application, such as those providing online banking functionality, cross-site scripting should always be considered high risk.]]></issueBackground>
    <remediationBackground><![CDATA[In most situations where user-controllable data is copied into application responses, cross-site scripting attacks can be prevented using two layers of defenses:<ul><li>Input should be validated as strictly as possible on arrival, given the kind of content which it is expected to contain. For example, personal names should consist of alphabetical and a small range of typographical characters, and be relatively short; a year of birth should consist of exactly four numerals; email addresses should match a well-defined regular expression. Input which fails the validation should be rejected, not sanitized.</li><li>User input should be HTML-encoded at any point where it is copied into application responses. All HTML metacharacters, including &lt; &gt; " ' and =, should be replaced with the corresponding HTML entities (&amp;lt; &amp;gt; etc).</li></ul>In cases where the application's functionality allows users to author content using a restricted subset of HTML tags and attributes (for example, blog comments which allow limited formatting and linking), it is necessary to parse the supplied HTML to validate that it does not use any dangerous syntax; this is a non-trivial task.]]></remediationBackground>
    <issueDetail><![CDATA[The value of the <b>q</b> request parameter is copied into the HTML document as plain text between tags. The payload <b>5d4ff&lt;script&gt;alert(1)&lt;/script&gt;18327</b> was submitted in the q parameter. This input was echoed unmodified in the application's response.<br><br>This proof-of-concept attack demonstrates that it is possible to inject arbitrary JavaScript into the application's response.]]></issueDetail>
    <requestresponse>
      <request method="GET" base64="true"><![CDATA[R0VUIC9ib2RnZWl0L3NlYXJjaC5qc3A/cT01NTUtNTU1LTAxOTlAZXhhbXBsZS5jb201ZDRmZjxzY3JpcHQ+YWxlcnQoMSk8JTJmc2NyaXB0PjE4MzI3IEhUVFAvMS4xDQpIb3N0OiBid2ENCkFjY2VwdDogKi8qDQpBY2NlcHQtTGFuZ3VhZ2U6IGVuDQpVc2VyLUFnZW50OiBNb3ppbGxhLzUuMCAoY29tcGF0aWJsZTsgTVNJRSA5LjA7IFdpbmRvd3MgTlQgNi4xOyBXaW42NDsgeDY0OyBUcmlkZW50LzUuMCkNCkNvbm5lY3Rpb246IGNsb3NlDQpSZWZlcmVyOiBodHRwOi8vYndhL2JvZGdlaXQvc2VhcmNoLmpzcA0KQ29va2llOiBhY29wZW5kaXZpZHM9c3dpbmdzZXQsam90dG8scGhwYmIyLHJlZG1pbmU7IGFjZ3JvdXBzd2l0aHBlcnNpc3Q9bmFkYTsgSlNFU1NJT05JRD1BRDAwMjQwQTkzMjgzNUVERDYwQjNGNzQ4N0E5RDE1RDsgUEhQU0VTU0lEPWhzaTZxcTFiYnA4Z3JnNmFoajk1czF1ZHY0OyBiX2lkPTk1DQoNCg==]]></request>
      <response base64="true"><![CDATA[SFRUUC8xLjEgMjAwIE9LDQpEYXRlOiBTYXQsIDEzIFNlcCAyMDE0IDIwOjI1OjI0IEdNVA0KU2VydmVyOiBBcGFjaGUtQ295b3RlLzEuMQ0KQ29udGVudC1UeXBlOiB0ZXh0L2h0bWwNCkNvbnRlbnQtTGVuZ3RoOiAyMDY0DQpWaWE6IDEuMSAxMjcuMC4xLjENClZhcnk6IEFjY2VwdC1FbmNvZGluZw0KQ29ubmVjdGlvbjogY2xvc2UNCg0KCgoKCgoKCjwhRE9DVFlQRSBIVE1MIFBVQkxJQyAiLS8vVzNDLy9EVEQgSFRNTCAzLjIvL0VOIj4KPGh0bWw+CjxoZWFkPgo8dGl0bGU+VGhlIEJvZGdlSXQgU3RvcmU8L3RpdGxlPgo8bGluayBocmVmPSJzdHlsZS5jc3MiIHJlbD0ic3R5bGVzaGVldCIgdHlwZT0idGV4dC9jc3MiIC8+CjxzY3JpcHQgdHlwZT0idGV4dC9qYXZhc2NyaXB0IiBzcmM9Ii4vanMvdXRpbC5qcyI+PC9zY3JpcHQ+CjwvaGVhZD4KPGJvZHk+Cgo8Y2VudGVyPgo8dGFibGUgd2lkdGg9IjgwJSIgY2xhc3M9ImJvcmRlciI+Cjx0ciBCR0NPTE9SPSNDM0Q5RkY+Cjx0ZCBhbGlnbj0iY2VudGVyIiBjb2xzcGFuPSI2Ij4KPEgxPlRoZSBCb2RnZUl0IFN0b3JlPC9IMT4KPHRhYmxlIHdpZHRoPSIxMDAlIiBjbGFzcz1cIm5vYm9yZGVyXCI+Cjx0ciBCR0NPTE9SPSNDM0Q5RkY+Cjx0ZCBhbGlnbj0iY2VudGVyIiB3aWR0aD0iMzAlIj4mbmJzcDs8L3RkPgo8dGQgYWxpZ249ImNlbnRlciIgd2lkdGg9IjQwJSI+V2UgYm9kZ2UgaXQsIHNvIHlvdSBkb250IGhhdmUgdG8hPC90ZD4KPHRkIGFsaWduPSJjZW50ZXIiIHdpZHRoPSIzMCUiIHN0eWxlPSJ0ZXh0LWFsaWduOiByaWdodCIgPgpHdWVzdCB1c2VyCgo8L3RyPgo8L3RhYmxlPgo8L3RkPgo8L3RyPgo8dHI+Cjx0ZCBhbGlnbj0iY2VudGVyIiB3aWR0aD0iMTYlIiBCR0NPTE9SPSNFRUVFRUU+PGEgaHJlZj0iaG9tZS5qc3AiPkhvbWU8L2E+PC90ZD4KPHRkIGFsaWduPSJjZW50ZXIiIHdpZHRoPSIxNiUiIEJHQ09MT1I9I0VFRUVFRT48YSBocmVmPSJhYm91dC5qc3AiPkFib3V0IFVzPC9hPjwvdGQ+Cgo8dGQgYWxpZ249ImNlbnRlciIgd2lkdGg9IjE2JSIgQkdDT0xPUj0jRUVFRUVFPjxhIGhyZWY9ImNvbnRhY3QuanNwIj5Db250YWN0IFVzPC9hPjwvdGQ+CjwhLS0gdGQgYWxpZ249ImNlbnRlciIgd2lkdGg9IjE2JSI+PGEgaHJlZj0iYWRtaW4uanNwIj5BZG1pbjwvYT48L3RkLS0+Cgo8dGQgYWxpZ249ImNlbnRlciIgd2lkdGg9IjE2JSIgQkdDT0xPUj0jRUVFRUVFPgoKCQk8YSBocmVmPSJsb2dpbi5qc3AiPkxvZ2luPC9hPgoKPC90ZD4KCjx0ZCBhbGlnbj0iY2VudGVyIiB3aWR0aD0iMTYlIiBCR0NPTE9SPSNFRUVFRUU+PGEgaHJlZj0iYmFza2V0LmpzcCI+WW91ciBCYXNrZXQ8L2E+PC90ZD4KCjx0ZCBhbGlnbj0iY2VudGVyIiB3aWR0aD0iMTYlIiBCR0NPTE9SPSNFRUVFRUU+PGEgaHJlZj0ic2VhcmNoLmpzcCI+U2VhcmNoPC9hPjwvdGQ+CjwvdHI+Cjx0cj4KPHRkIGFsaWduPSJjZW50ZXIiIGNvbHNwYW49IjYiPgo8dGFibGUgd2lkdGg9IjEwMCUiIGNsYXNzPSJib3JkZXIiPgo8dHI+Cjx0ZCBhbGlnbj0ibGVmdCIgdmFsaWduPSJ0b3AiIHdpZHRoPSIyNSUiPgo8YSBocmVmPSJwcm9kdWN0LmpzcD90eXBlaWQ9NiI+RG9vZGFoczwvYT48YnIvPgo8YSBocmVmPSJwcm9kdWN0LmpzcD90eXBlaWQ9NSI+R2l6bW9zPC9hPjxici8+CjxhIGhyZWY9InByb2R1Y3QuanNwP3R5cGVpZD0zIj5UaGluZ2FtYWppZ3M8L2E+PGJyLz4KPGEgaHJlZj0icHJvZHVjdC5qc3A/dHlwZWlkPTIiPlRoaW5naWVzPC9hPjxici8+CjxhIGhyZWY9InByb2R1Y3QuanNwP3R5cGVpZD03Ij5XaGF0Y2hhbWFjYWxsaXRzPC9hPjxici8+CjxhIGhyZWY9InByb2R1Y3QuanNwP3R5cGVpZD00Ij5XaGF0c2l0czwvYT48YnIvPgo8YSBocmVmPSJwcm9kdWN0LmpzcD90eXBlaWQ9MSI+V2lkZ2V0czwvYT48YnIvPgoKPGJyLz48YnIvPjxici8+PGJyLz48YnIvPjxici8+PGJyLz48YnIvPjxici8+PGJyLz48YnIvPjxici8+PGJyLz48YnIvPjxici8+CjwvdGQ+Cjx0ZCB2YWxpZ249InRvcCIgd2lkdGg9IjcwJSI+Cgo8aDM+U2VhcmNoPC9oMz4KPGZvbnQgc2l6ZT0iLTEiPgoKPGI+WW91IHNlYXJjaGVkIGZvcjo8L2I+IDU1NS01NTUtMDE5OUBleGFtcGxlLmNvbTVkNGZmPHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0PjE4MzI3PGJyLz48YnIvPgo8ZGl2PjxiPk5vIFJlc3VsdHMgRm91bmQ8L2I+PC9kaXY+Cgo8L2ZvbnQ+CjwvdGQ+CjwvdHI+CjwvdGFibGU+CjwvdGQ+CjwvdHI+CjwvdGFibGU+CjwvY2VudGVyPgo8L2JvZHk+CjwvaHRtbD4K]]></response>
      <responseRedirected>false</responseRedirected>
    </requestresponse>
  </issue>
  <issue>
    <serialNumber>7121655797013284864</serialNumber>
    <type>1049088</type>
    <name>SQL injection</name>
    <host ip="192.168.187.137">http://bwa</host>
    <path><![CDATA[/bodgeit/basket.jsp]]></path>
    <location><![CDATA[/bodgeit/basket.jsp [b_id cookie]]]></location>
    <severity>High</severity>
    <confidence>Firm</confidence>
    <issueBackground><![CDATA[SQL injection vulnerabilities arise when user-controllable data is incorporated into database SQL queries in an unsafe manner. An attacker can supply crafted input to break out of the data context in which their input appears and interfere with the structure of the surrounding query.<br><br>Various attacks can be delivered via SQL injection, including reading or modifying critical application data, interfering with application logic, escalating privileges within the database and executing operating system commands.]]></issueBackground>